# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npx eslint .
    - run: npm test -- --passWithNoTests
      env:
        CI: true
        DATABASE_URL: postgres://ehbddyzysgzhdv:089ba9c258db50f97a43cfc92c30fa97db2a93c56419547007e3509fb85e727b@ec2-35-174-35-242.compute-1.amazonaws.com:5432/d514au0k4bqi45
